<script type="text/javascript">

jQuery(document).ready(function() {

	jQuery(".type-select").selectbox();

	jQuery(".color-box select").selectbox();

});

</script>
<?php
	$_productCollection = Mage::getModel('catalog/product')->getCollection();
	$_productCollection->addAttributeToFilter('create_by', array('gt' =>0))->addAttributeToSelect('*');
    $_helper = $this->helper('catalog/output');
	$customerName = Mage::getSingleton('customer/session')->getCustomer()->getName();
?>



<?php if(!$_productCollection->count()): ?>

<div class="box-content category-grid">

    <div class="category-products">

		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>

	</div>

</div>

<?php else: ?>



<div class="box-content category-grid">

    <div class="category-products">

        <div class="sorter">

            <div class="sort-by">

                Sort By: <?php

				$tool = Mage::getSingleton('Mage_Catalog_Block_Product_List_Toolbar');

            	foreach($tool->getAvailableOrders() as $_key=>$_order):

				?>

					<a <?php if($tool->isOrderCurrent($_key)): echo 'class="current"'; endif; ?> href="<?php echo $tool->getOrderUrl($_key, 'desc') ?>"><?php if($_key == 'position'): echo 'Recommended'; else: echo $this->__($_order); endif; ?></a>

            	<?php endforeach; ?>

                <?php if($tool->getCurrentDirection() == 'desc'): ?>

                <a href="<?php echo $tool->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/icon_tool_d.png') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>

                <?php else: ?>

                    <a href="<?php echo $tool->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/icon_tool_a.png') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>

                <?php endif; ?>

            </div>

        </div>

        <?php echo $this->getToolbarHtml() ?>

        <ul class="products-grid">

        	<?php foreach ($_productCollection as $_product): ?>

            <li class="item">

                <div class="item-content">

                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(148); ?>" width="148" height="148" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <h2 class="product-name"><a href="#"><?php echo $customerName; ?></a></h2>

                    <?php echo $this->getPriceHtml($_product, true) ?>

                    <?php if($_product->isSaleable()): ?>

                    <div class="actions">

                        <label>Qty:</label>

                        <input style="width:35px; height: 19px; margin-top: 1px;" type="text" id="qty" value="1" />

                        <button data-url="<?php echo $this->getAddToCartUrl($_product) ?>" class="button btn-cart" title="Add to Cart" type="button"><span><span>Add to Cart</span></span></button>

                    </div>

                    <?php else: ?>

                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>

                    <?php endif; ?>

                    <p class="description"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>

                </div>

            </li>

            <?php endforeach; ?>

        </ul><!-- // products grid -->

        <?php echo $this->getToolbarHtml() ?>
    </div>

    

</div>

<?php endif; ?>

<script type="text/javascript">

jQuery(document).ready(function(e) {

    jQuery(".btn-cart").click(function(e) {

		//window.location = jQuery(this).data('url') + 'qty/'+jQuery(this).parent('.actions').find('.jquery-selectbox-currentItem').text()+'/';
		window.location = jQuery(this).data('url') + 'qty/'+jQuery(this).parent('.actions').find('#qty').val()+'/';

    });

});

</script>