<?php if(Mage::getStoreConfig('general/home_config/home_facebook_fanpage') != ''): ?>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="box">
    <div class="box-title"><strong>Find Us on Facebook</strong></div>
    <div class="box-content">
        <div class="fb-like-box" data-href="<?php echo Mage::getStoreConfig('general/home_config/home_facebook_fanpage'); ?>" data-width="200" data-height="320" data-show-faces="true" data-stream="false" data-header="false"></div>
    </div>
</div>
<?php endif; ?>