<div class="blocks">

    <div class="blocks-title">

        我要卖 <strong>I Want to Sell</strong>

    </div>                  

    <div class="blocks-content">  	

        <ol>

            <li><a href="#">Diaper</a></li>

            <li><a href="#">Brands</a></li>

            <li><a href="#">Nivea</a></li>

            <li><a href="#">iPhone</a></li>

            <li><a href="#">Ipoh Coffee</a></li>

        </ol>

    </div>

</div>